import React from 'react'

const LABELS = {
  en: {
    riskAlerts: 'Risk Alerts',
    labResults: 'Lab Results',
    recommendations: 'Recommendations',
    recSub: 'Evidence-based clinical suggestions',
    trend: 'Trend Analysis',
    trendSub: 'Longitudinal health tracking',
    comparison: 'Report Comparison',
    compSub: 'Changes between reports',
    noInsights: 'No insights yet.',
    noInsightsSub: 'Upload a medical document to get AI-powered clinical analysis.',
    exportPdf: '📄 Export PDF',
    shareWa: '💬 WhatsApp',
    improved: 'improved',
    worsened: 'worsened',
    params: 'parameters analyzed',
    alerts: 'alerts detected',
  },
  hi: {
    riskAlerts: 'जोखिम अलर्ट',
    labResults: 'लैब रिजल्ट',
    recommendations: 'सिफारिशें',
    recSub: 'साक्ष्य-आधारित नैदानिक सुझाव',
    trend: 'ट्रेंड विश्लेषण',
    trendSub: 'दीर्घकालिक स्वास्थ्य ट्रैकिंग',
    comparison: 'रिपोर्ट तुलना',
    compSub: 'रिपोर्ट के बीच परिवर्तन',
    noInsights: 'अभी कोई जानकारी नहीं।',
    noInsightsSub: 'AI विश्लेषण के लिए एक मेडिकल डॉक्यूमेंट अपलोड करें।',
    exportPdf: '📄 PDF निर्यात',
    shareWa: '💬 WhatsApp',
    improved: 'सुधार',
    worsened: 'बिगड़ा',
    params: 'पैरामीटर विश्लेषित',
    alerts: 'अलर्ट पाए गए',
  },
}

function generatePDF(insights, findings) {
  // Create print-friendly content and trigger browser print dialog
  const printContent = `
    <html>
    <head>
      <title>NovaDoc - Health Report</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1a1a2e; }
        h1 { color: #0d47a1; border-bottom: 2px solid #0d47a1; padding-bottom: 8px; }
        h2 { color: #1565c0; margin-top: 24px; }
        .alert { padding: 12px 16px; margin: 8px 0; border-radius: 8px; border-left: 4px solid; }
        .alert.high { background: #fff3f3; border-color: #d32f2f; }
        .alert.medium { background: #fff8e1; border-color: #f9a825; }
        .alert.low { background: #e8f5e9; border-color: #2e7d32; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; font-size: 13px; }
        th { background: #e3f2fd; }
        .badge { padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
        .badge.normal { background: #e8f5e9; color: #2e7d32; }
        .badge.high { background: #ffebee; color: #c62828; }
        .badge.low { background: #fff3e0; color: #e65100; }
        ul { padding-left: 20px; }
        li { margin: 6px 0; line-height: 1.5; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>🧬 NovaDoc Health Report</h1>
      <p><em>Generated on ${new Date().toLocaleDateString()}</em></p>
      
      ${insights?.riskAlerts?.length ? `
        <h2>⚠️ Risk Alerts</h2>
        ${insights.riskAlerts.map(a => `
          <div class="alert ${a.severity}">
            <strong>${a.severity.toUpperCase()}: ${a.title}</strong><br/>
            ${a.detail}
          </div>
        `).join('')}
      ` : ''}

      ${findings?.length ? `
        <h2>📊 Lab Results</h2>
        <table>
          <thead><tr><th>Test</th><th>Value</th><th>Reference</th><th>Status</th></tr></thead>
          <tbody>
            ${findings.map(f => `
              <tr>
                <td>${f.test}</td>
                <td>${f.value}</td>
                <td>${f.range}</td>
                <td><span class="badge ${f.status}">${f.status}</span></td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}

      ${insights?.recommendations?.length ? `
        <h2>💡 Recommendations</h2>
        <ul>
          ${insights.recommendations.map(r => `<li>${r}</li>`).join('')}
        </ul>
      ` : ''}

      <div class="footer">
        Generated by NovaDoc – AI Medical Document Intelligence | Powered by Amazon Nova<br/>
        ⚕️ This is an AI-generated summary. Always consult your healthcare provider.
      </div>
    </body>
    </html>
  `
  const printWindow = window.open('', '_blank')
  printWindow.document.write(printContent)
  printWindow.document.close()
  printWindow.print()
}

export default function InsightsPanel({ insights, findings, comparison, lang = 'en', onWhatsAppShare }) {
  const L = LABELS[lang]

  if (!insights) {
    return (
      <div className="glass-card">
        <div className="card-header">
          <div className="card-header-icon orange">🔍</div>
          <div>
            <h2>{lang === 'hi' ? 'नैदानिक जानकारी' : 'Clinical Insights'}</h2>
            <p>{lang === 'hi' ? 'आपके मेडिकल डेटा का AI विश्लेषण' : 'AI-generated analysis of your medical data'}</p>
          </div>
        </div>
        <div className="timeline-empty">
          <div className="timeline-empty-icon">🔬</div>
          <p>{L.noInsights}<br/>{L.noInsightsSub}</p>
        </div>
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* Action Buttons */}
      <div className="insight-actions">
        <button className="action-btn pdf" onClick={() => generatePDF(insights, findings)}>
          {L.exportPdf}
        </button>
        <button className="action-btn whatsapp" onClick={onWhatsAppShare}>
          {L.shareWa}
        </button>
      </div>

      {/* Risk Alerts */}
      {insights.riskAlerts && insights.riskAlerts.length > 0 && (
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon orange">⚠️</div>
            <div>
              <h2>{L.riskAlerts}</h2>
              <p>{insights.riskAlerts.length} {L.alerts}</p>
            </div>
          </div>
          <div className="insights-container">
            {insights.riskAlerts.map((alert, i) => (
              <div key={i} className={`insight-alert ${alert.severity}`}>
                <div className="insight-alert-header">
                  <span className="insight-alert-severity">
                    {alert.severity === 'high' ? '🔴' : alert.severity === 'medium' ? '🟡' : '🟢'} {alert.severity}
                  </span>
                </div>
                <h4>{alert.title}</h4>
                <p>{alert.detail}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Findings Table */}
      {findings && findings.length > 0 && (
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon cyan">📊</div>
            <div>
              <h2>{L.labResults}</h2>
              <p>{findings.length} {L.params}</p>
            </div>
          </div>
          <div style={{ overflowX: 'auto' }}>
            <table className="findings-table">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>Value</th>
                  <th>Reference</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {findings.map((f, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 500, color: 'var(--text-primary)' }}>{f.test}</td>
                    <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem' }}>{f.value}</td>
                    <td style={{ fontSize: '0.7rem' }}>{f.range}</td>
                    <td>
                      <span className={`status-badge ${f.status}`}>{f.status}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Multi-doc Comparison */}
      {comparison && comparison.trends && comparison.trends.length > 0 && (
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon cyan">🔄</div>
            <div>
              <h2>{L.comparison}</h2>
              <p>{L.compSub}</p>
            </div>
          </div>
          <div style={{ overflowX: 'auto' }}>
            <table className="findings-table">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>{comparison.previousDate}</th>
                  <th>{comparison.latestDate}</th>
                  <th>Change</th>
                  <th>Trend</th>
                </tr>
              </thead>
              <tbody>
                {comparison.trends.map((t, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 500, color: 'var(--text-primary)' }}>{t.test}</td>
                    <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem' }}>{t.previousValue}</td>
                    <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem' }}>{t.currentValue}</td>
                    <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem', color: t.improved ? '#4caf50' : '#ff5252' }}>
                      {t.change} ({t.percentChange})
                    </td>
                    <td>
                      <span className={`status-badge ${t.improved ? 'normal' : 'high'}`}>
                        {t.direction === 'increased' ? '📈' : '📉'} {t.improved ? L.improved : L.worsened}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Recommendations */}
      {insights.recommendations && insights.recommendations.length > 0 && (
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon green">💡</div>
            <div>
              <h2>{L.recommendations}</h2>
              <p>{L.recSub}</p>
            </div>
          </div>
          <ul className="recommendations-list">
            {insights.recommendations.map((rec, i) => (
              <li key={i}>{rec}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Trend Analysis */}
      {insights.trendAnalysis && (
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon purple">📈</div>
            <div>
              <h2>{L.trend}</h2>
              <p>{L.trendSub}</p>
            </div>
          </div>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {insights.trendAnalysis}
          </p>
        </div>
      )}
    </div>
  )
}
