import React, { useState, useCallback, useEffect } from 'react'
import UploadPanel from './components/UploadPanel'
import Timeline from './components/Timeline'
import ChatPanel from './components/ChatPanel'
import InsightsPanel from './components/InsightsPanel'
import DocumentModal from './components/DocumentModal'
import DrugInteractions from './components/DrugInteractions'
import FamilyVault from './components/FamilyVault'

// UI labels in both languages
const LABELS = {
  en: {
    title: 'NovaDoc',
    subtitle: 'AI Medical Document Intelligence',
    badge: 'Powered by Amazon Nova',
    upload: '📤 Upload',
    insights: '🔍 Insights',
    timeline: '📋 Timeline',
    drugs: '💊 Drugs',
    chat: 'Ask NovaDoc',
    chatSub: 'Chat about your medical records',
    family: 'Family Vault',
    langBtn: 'हिंदी',
  },
  hi: {
    title: 'NovaDoc',
    subtitle: 'AI मेडिकल डॉक्यूमेंट इंटेलिजेंस',
    badge: 'Amazon Nova द्वारा संचालित',
    upload: '📤 अपलोड',
    insights: '🔍 जानकारी',
    timeline: '📋 समयरेखा',
    drugs: '💊 दवाइयाँ',
    chat: 'NovaDoc से पूछें',
    chatSub: 'अपने मेडिकल रिकॉर्ड के बारे में बात करें',
    family: 'परिवार वॉल्ट',
    langBtn: 'English',
  },
}

function App() {
  const [documents, setDocuments] = useState([])
  const [selectedDoc, setSelectedDoc] = useState(null)
  const [activeTab, setActiveTab] = useState('upload')
  const [isProcessing, setIsProcessing] = useState(false)
  const [lang, setLang] = useState('en')
  const [comparison, setComparison] = useState(null)
  const [showFamily, setShowFamily] = useState(false)
  const [activeProfile, setActiveProfile] = useState({ name: 'My Records', avatar: '🧑' })

  const L = LABELS[lang]

  // Hydrate from server on mount
  useEffect(() => {
    fetch('/api/documents')
      .then(r => r.json())
      .then(data => {
        if (data.documents && data.documents.length > 0) {
          setDocuments(data.documents.reverse())
          setActiveTab('insights')
        }
      })
      .catch(() => {})

    fetch('/api/profiles')
      .then(r => r.json())
      .then(data => {
        const active = data.profiles.find(p => p.id === data.activeProfile)
        if (active) setActiveProfile(active)
      })
      .catch(() => {})
  }, [])

  const handleDocumentProcessed = useCallback((doc, comp) => {
    setDocuments(prev => [doc, ...prev])
    if (comp) setComparison(comp)
    setActiveTab('insights')
  }, [])

  const handleProfileSwitch = useCallback(async (profileId) => {
    await fetch('/api/profiles/switch', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ profileId }),
    })
    const res = await fetch('/api/documents')
    const data = await res.json()
    setDocuments(data.documents?.reverse() || [])

    const pRes = await fetch('/api/profiles')
    const pData = await pRes.json()
    const active = pData.profiles.find(p => p.id === profileId)
    if (active) setActiveProfile(active)
    setActiveTab(data.documents?.length > 0 ? 'insights' : 'upload')
    setShowFamily(false)
  }, [])

  const latestInsights = documents.length > 0 ? documents[0].insights : null
  const allFindings = documents.flatMap(d =>
    (d.extraction?.findings || []).map(f => ({ ...f, docDate: d.extraction?.date, docType: d.extraction?.documentType }))
  )
  const allMedications = [...new Set(documents.flatMap(d => d.extraction?.medications || []))]

  // WhatsApp share
  const handleWhatsAppShare = () => {
    if (!latestInsights) return
    const text = `🧬 NovaDoc Health Summary\n\n` +
      `⚠️ Risk Alerts:\n${latestInsights.riskAlerts?.map(a => `• ${a.title}`).join('\n') || 'None'}\n\n` +
      `💡 Recommendations:\n${latestInsights.recommendations?.map(r => `• ${r}`).join('\n') || 'None'}\n\n` +
      `Generated by NovaDoc - AI Medical Document Intelligence`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank')
  }

  return (
    <div className="app-container">
      <header className="app-header">
        <div className="app-logo">
          <div className="app-logo-icon">🧬</div>
          <div>
            <h1>{L.title}</h1>
            <span>{L.subtitle}</span>
          </div>
        </div>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {/* Family Profile Selector */}
          <button className="header-action-btn" onClick={() => setShowFamily(!showFamily)}>
            {activeProfile.avatar} {activeProfile.name}
          </button>
          {/* Language Toggle */}
          <button className="header-action-btn lang-toggle" onClick={() => setLang(lang === 'en' ? 'hi' : 'en')}>
            🌐 {L.langBtn}
          </button>
          <div className="header-badge">
            <div className="dot"></div>
            {L.badge}
          </div>
        </div>
      </header>

      {/* Family Vault Modal */}
      {showFamily && (
        <FamilyVault
          onClose={() => setShowFamily(false)}
          onSwitch={handleProfileSwitch}
          activeProfile={activeProfile}
        />
      )}

      <div className="main-layout">
        {/* LEFT COLUMN */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <div className="tabs">
            <button className={`tab-btn ${activeTab === 'upload' ? 'active' : ''}`} onClick={() => setActiveTab('upload')}>
              {L.upload}
            </button>
            <button className={`tab-btn ${activeTab === 'insights' ? 'active' : ''}`} onClick={() => setActiveTab('insights')}>
              {L.insights}
            </button>
            <button className={`tab-btn ${activeTab === 'timeline' ? 'active' : ''}`} onClick={() => setActiveTab('timeline')}>
              {L.timeline}
            </button>
            <button className={`tab-btn ${activeTab === 'drugs' ? 'active' : ''}`} onClick={() => setActiveTab('drugs')}>
              {L.drugs}
            </button>
          </div>

          {activeTab === 'upload' && (
            <UploadPanel
              onDocumentProcessed={handleDocumentProcessed}
              isProcessing={isProcessing}
              setIsProcessing={setIsProcessing}
              lang={lang}
            />
          )}

          {activeTab === 'insights' && (
            <InsightsPanel
              insights={latestInsights}
              findings={allFindings}
              comparison={comparison}
              lang={lang}
              onWhatsAppShare={handleWhatsAppShare}
            />
          )}

          {activeTab === 'timeline' && (
            <Timeline
              documents={documents}
              onSelectDocument={setSelectedDoc}
            />
          )}

          {activeTab === 'drugs' && (
            <DrugInteractions
              medications={allMedications}
              interactions={latestInsights?.drugInteractions || []}
              lang={lang}
            />
          )}
        </div>

        {/* RIGHT COLUMN - Chat */}
        <div className="glass-card">
          <div className="card-header">
            <div className="card-header-icon purple">💬</div>
            <div>
              <h2>{L.chat}</h2>
              <p>{L.chatSub}</p>
            </div>
          </div>
          <ChatPanel documents={documents} lang={lang} />
        </div>
      </div>

      {selectedDoc && (
        <DocumentModal
          document={selectedDoc}
          onClose={() => setSelectedDoc(null)}
        />
      )}
    </div>
  )
}

export default App
